server:
  port: 5678

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: xams
    password: xpar
    driver-class-name: com.mysql.cj.jdbc.Driver

# 打印SQL
logging:
  level:
    com.example.dao: debug

mybatis:
  # XML扫描路径
  mapper-locations: classpath:mapper/**/*.xml
  # 通用Mapper的方法会自动转换驼峰，但手写的SQL需要开启才能转换
  configuration:
    map-underscore-to-camel-case: on
